### ISSUE TITLE
Do not show the deleted values in the final matrix

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#116]
#112 correctly hides the deleted values , but it should only be done in the working matrix
The deleted values should not be visible in the final matrix.

**Comment by gonzomir** [comment]
Deleted data is not visible in the final matrix if it has been deleted before the final matrix is created. If it is deleted after the final matrix is created, this data is present in the final matrix because the final matrix is separate entity.

**Comment by vedina** [comment]
In any case the data flagged as "deleted" should not be visible in the final matrix (same as the old behaviour of both matrices)

**Comment by gonzomir** [comment]
It is not flagged as deleted because the final matrix is a snapshot of the working matrix before the data is deleted. Data in final matrix represents the state of the working matrix at the time it is created and later changes in the working matrix are not visible in any way in the final matrix.
https://github.com/ideaconsult/Toxtree.js/issues/78#issuecomment-70408630

**Comment by vedina** [comment]
What is required is 

* if there are data entries flagged as `deleted` in the final matrix, they will not be shown.

Please confirm this is the behaviour.

**Comment by gonzomir** [comment]
This is the exact behaviour.

**Comment by vedina** [comment]
OK!

**Comment by vedina** [comment]
The server is modified to always send the working matrix, hence the content will always be the same, but the final matrix will hide the deleted values.
