### ISSUE TITLE
jToxKit versioning

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#192]
Could we introduce versioning for jToxKit ?  @thejonan , @gonzomir  - proposals welcome.

**Comment by gonzomir** [comment]
What do you mean by versioning? If you mean support two or more versions in parallel, we can create branches for each version and merge only fixes to the old versions and new features to the one in development. If you mean realising versions of jToxKit, we should look ad Github Releases:
https://help.github.com/articles/creating-releases/
https://github.com/blog/1547-release-your-software

**Comment by vedina** [comment]
No, I mean being able to say this is jToxKit version 3.14

**Comment by gonzomir** [comment]
Got it, then maybe a version property on the jT object (and possibly on every kit). We will have to remember to bump the version number when releasing or find a way to automate it.

**Comment by thejonan** [comment]
Hm... yes - a property in jT object is definitely a good choice. Whether we need versions of submodule is related also to (1) the testing system, we're about to integrate at some point, and (2) how independent the separate kits are. I don't think they are, or will ever be - let's keep in mind that `ui_XXX` things are _not_ part of the kit, but it's use cases.

What I'd suggest is the following:
* I can change the building script so that, if given a version string, it appends it to the packages' js files and also makes a git tagging.
* This can later be integrate into automated testing platform.

**Comment by thejonan** [comment]
I've added corresponding property and altered the building script to extract the value from there and append it to output files (`.js` and `.css`). No automatic changes on `git` are performed, however. This can happen when integrate along with some unit testing kit.

**Comment by vedina** [comment]
Not completely solved, but moved to https://github.com/ideaconsult/jToxKit/issues/32
