### ISSUE TITLE
Update http://ideaconsult.github.io/Toxtree.js/

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#95]
The page at http://ideaconsult.github.io/Toxtree.js/ is used as a demo to display a dataset with links to [WikiPathways](http://www.wikipathways.org/index.php/WikiPathways)

The goal is to show only chemical names an InChI , and a single column with names of all the pathways corresponding to a compound, with links to each specific pathway (e.g. [Pathway:WP399](http://www.wikipathways.org/index.php/Pathway:WP399) )
@egonw may clarify if there are other requirements.

1) The [dataset used](https://apps.ideaconsult.net/data/dataset/54?media=application%2Fjson)
2) The page to be updated [index.html at gh-pages branch](https://github.com/ideaconsult/Toxtree.js/blob/gh-pages/index.html) It contains an ([outdated](https://github.com/ideaconsult/Toxtree.js/commit/b24f857e8108f7e9289a49753948a4ef046bb4d2#diff-eacf331f0ffc35d4b482f1d15a887d3b)) custom configuration config_dataset, which should be replaced with the current mechanism of accumulating values in a dataset column. 
@thejonan may help with pointing to the relevant part of the documentation.

**Comment by thejonan** [comment]
The information regarding `jToxCompound` configuration can be found in the [README.md](https://github.com/ideaconsult/Toxtree.js) of the repository, under section [jToxCompound/Configuration](https://github.com/ideaconsult/Toxtree.js#configuration). I've made a few updates, but nothing important.

Also, exemplary configurations can be found in [ui-matrix's configuration](https://github.com/ideaconsult/Toxtree.js/blob/master/uses/config-matrix.js) and in [ui-query's configuration](https://github.com/ideaconsult/Toxtree.js/blob/master/uses/config-dataset.js).

I'm not sure which aspect of value accumulation is referred, but the general idea is that since more than one feature can refer to a same value (via `sameAs` property), it occurs that these many values has to be dealt somehow and the `fnAccumulate` function (which is part of *jToxCompound's* settings) takes this role. What data property each feature is pointing is given with `data` property from feature's definition and whether the value should be accumulated there is given from... `accumulate` property. Default `baseFeatures` in *jToxCompound* is a good place for examples regarding this.

**Comment by gonzomir** [comment]
The configuration is updated, a fnAccumulate function gathers all the pathways as a list of links. Also the page HTML and CSS got some improvements.

**Comment by vedina** [comment]
Completed.

@egonw - could you please check the dataset uploaded - it seems to contain duplicate compounds, WPM features without links and is missing the chemical names. If necessary remove and upload it again.
